package ir.utopia.common.doctype.persistent;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * CmDocStatus 
 */
@Entity
@Table(name = "CM_DOC_STATUS",  uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CM_DOCTYPE_ID", "STATUS_NAME", "CM_FISCALYEAR_ID" }) })
@TableGenerator(name = "DocstatusSequenceGenerator", 
table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CM_DOC_STATUS")
public class CmDocStatus extends AbstractCmDocStatus implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = -591213503330867216L;

	/** default constructor */
	public CmDocStatus() {
	}

	public CmDocStatus(CmDocStatus status,Long coUsecaseId) {
		this.setCmDocStatusId(status.getCmDocStatusId());
		this.setCmFiscalyear(status.getCmFiscalyear());
		this.setCmDoctype(status.getCmDoctype());
		this.setStatusName(status.getStatusName());
		this.setLockAble(status.getLockAble());
		this.setSkipAble(status.getSkipAble());
		this.setCmTransitionsForCmDocStatusTo(status.getCmTransitionsForCmDocStatusTo()); 
		this.setCmTransitionsForCmDocStatusFrom(status.getCmTransitionsForCmDocStatusFrom());
		this.setStatus(status.getStatus());
		this.setCoUseCaseId(coUsecaseId);
	}
	private Long coUseCaseId;
	@Transient
	public Long getCoUseCaseId() {
		return coUseCaseId;
	}

	public void setCoUseCaseId(Long coUseCaseId) {
		this.coUseCaseId = coUseCaseId;
	}
	
}
