package ir.utopia.common.dashboard.persistent;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * 
 */
@Entity
@Table(name = "CM_TRANSITION_HISTORY", uniqueConstraints = {})
@TableGenerator(name = "TransitionHistorySequenceGenerator", 
table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CM_TRANSITION_HISTORY")
public class CmTransitionHistory extends AbstractCmTransitionHistory implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 2850213994851433967L;

	/** default constructor */
	public CmTransitionHistory() {
	}

	

}
