package ir.utopia.core.importer.settinginstance.persistent;


import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.UniqueConstraint;

/**
 * CoImporterInstance generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "CO_IMPORTER_INSTANCE", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"NAME", "CO_IMPORTER_SETTING_ID" }) })

@TableGenerator(name = "ImportInstanceGenerator", 
table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CO_IMPORTER_INSTANCE")
public class CoImporterInstance extends AbstractCoImporterInstance implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 7757754296078203863L;

	/** default constructor */
	public CoImporterInstance() {
	}

	

}
