package ir.utopia.core.security.roleorganizationaccess.persistent;
// default package
// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CoRoleOrganizationAcss generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "CO_ROLE_ORGANIZATION_ACSS",  uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CO_ROLE_ID", "CM_ORGANIZATION_ID" }) })
public class CoRoleOrganizationAcss extends AbstractCoRoleOrganizationAcss
		implements java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 3569536853041283658L;

	/** default constructor */
	public CoRoleOrganizationAcss() {
	}

	

}
