package ir.utopia.core.security.persistent;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CoUserAppToken generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "CO_USER_APP_TOKEN",  uniqueConstraints = {})
public class CoUserAppToken extends AbstractCoUserAppToken implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 3210024808072199484L;

	/** default constructor */
	public CoUserAppToken() {
	}

	
}
