package ir.utopia.core.security.userpreferences.persistent;

// Generated by MyEclipse Persistence Tools

import ir.utopia.core.security.user.persistence.CoUser;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.UniqueConstraint;

/**
 * CoUserPreferences
 */
@Entity
@Table(name = "CO_USER_PREFERENCES",  uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CO_USER_ID", "KEY" }) })
@TableGenerator(name = "CoUseprefernecesSequenceGenerator", 
table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CO_USER_PREFERENCES")
public class CoUserPreferences extends AbstractCoUserPreferences implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 392650479146495039L;

	/** default constructor */
	public CoUserPreferences() {
	}

	/** full constructor */
	public CoUserPreferences(Long coUserPreferencesId, CoUser coUser,
			String key, String value) {
		super(coUserPreferencesId, coUser, key, value);
	}

}
