package ir.utopia.core.security.userorganizationaccess.persistent;

// default package
// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CoUserOrganizationAcss 
 */
@Entity
@Table(name = "CO_USER_ORGANIZATION_ACSS", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CO_USER_ID", "CM_ORGANIZATION_ID" }) })
public class CoUserOrganizationAcss extends AbstractCoUserOrganizationAcss
		implements java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 514876249336447314L;

	/** default constructor */
	public CoUserOrganizationAcss() {
	}

	

}
