package ir.utopia.core.security.userorganizationaccess.persistent;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CoVValidOrgAccss 
 */
@Entity
@Table(name = "CO_V_VALID_ORG_ACCSS")
public class CoVValidOrgAccss extends AbstractCoVValidOrgAccss implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 2964327054313909017L;

	/** default constructor */
	public CoVValidOrgAccss() {
	}

	/** full constructor */
	public CoVValidOrgAccss(CoVValidOrgAccssId id) {
		super(id);
	}

}
